site_name: CV Rusty
repo_url: https://github.com/johnhalz/cv-rusty
repo_name: johnhalz/cv-rusty

nav:
  - Home: index.md
  - Quick Reference: quick-reference.md
  - Guides:
      - Color Conversion: guides/color-conversion-guide.md
      - Convolution: guides/convolution.md
      - Image Writing: guides/image-writing.md
      - Transform Operations: guides/transform_operations.md
      - Custom Rotation: guides/custom_rotation.md
      - Window Display: guides/window_display.md
  - Architecture:
      - Overview: architecture/architecture.md
      - Embedded Systems: architecture/embedded.md
  - Changelogs:
      - Color Features: changelogs/changelog-color-features.md
      - Window Feature: changelogs/window_feature_summary.md

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - search.suggest
    - content.tabs.link

plugins:
  - search

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
